<script setup>
import { onMounted, reactive, ref } from 'vue'
import { merchantApi } from '../api'
import { ElMessage } from 'element-plus'
const props=defineProps({orderNo:{type:String,required:true}});const order=ref(null);const shipDialog=ref(false);const shipping=reactive({shippingCompany:'',trackingNo:''});const loading=ref(false)
const labels={WAITING_SHIPMENT:'待发货',WAITING_RECEIPT:'待收货',COMPLETED:'已完成',REFUNDING:'退款中',REFUNDED:'已退款'};const money=c=>`¥${(Number(c||0)/100).toFixed(2)}`
async function load(){try{order.value=await merchantApi.order(props.orderNo)}catch(e){ElMessage.error(e.message)}}
async function ship(){loading.value=true;try{order.value=await merchantApi.shipOrder(props.orderNo,shipping);shipDialog.value=false;ElMessage.success('发货成功')}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
onMounted(load)
</script>
<template><el-card v-if="order"><template #header><div style="display:flex;justify-content:space-between"><strong>订单 {{order.orderNo}}</strong><el-tag>{{labels[order.status]||order.status}}</el-tag></div></template><dl class="detail-grid"><dt>支付金额</dt><dd>{{money(order.payAmountCent)}}</dd><dt>支付方式</dt><dd>{{order.paymentChannel}}</dd><dt>收货人</dt><dd>{{order.address.receiver}} {{order.address.phone}}</dd><dt>收货地址</dt><dd>{{order.address.province}}{{order.address.city}}{{order.address.district}}{{order.address.detail}}</dd><template v-if="order.trackingNo"><dt>物流信息</dt><dd>{{order.shippingCompany}} / {{order.trackingNo}}</dd></template></dl><el-divider>商品明细</el-divider><el-table :data="order.items"><el-table-column prop="productTitle" label="商品"/><el-table-column prop="specsJson" label="规格"/><el-table-column prop="quantity" label="数量"/><el-table-column label="小计"><template #default="s">{{money(s.row.subtotalCent)}}</template></el-table-column></el-table><el-button v-if="order.status==='WAITING_SHIPMENT'" type="primary" style="margin-top:18px" @click="shipDialog=true">填写物流并发货</el-button></el-card><el-dialog v-model="shipDialog" title="订单发货" width="460"><el-form label-width="90px"><el-form-item label="物流公司"><el-input v-model="shipping.shippingCompany"/></el-form-item><el-form-item label="运单号"><el-input v-model="shipping.trackingNo"/></el-form-item></el-form><template #footer><el-button @click="shipDialog=false">取消</el-button><el-button type="primary" :loading="loading" @click="ship">确认发货</el-button></template></el-dialog></template>
