<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { merchantApi } from '../api'
import { ElMessage } from 'element-plus'
const props=defineProps({id:{type:String,default:null}});const router=useRouter();const categories=ref([]);const image=ref(null);const saving=ref(false)
const form=reactive({title:'',description:'',categoryId:null,status:0,skus:[{id:null,specsText:'{"规格":"默认"}',priceYuan:0.01,stock:0,status:1}]})
function flatten(nodes,result=[]){for(const n of nodes||[]){result.push(n);flatten(n.children,result)}return result}
function pick(file){image.value=file.raw}
function addSku(){form.skus.push({id:null,specsText:'{"规格":"默认"}',priceYuan:0.01,stock:0,status:1})}
function payload(){return{title:form.title,description:form.description,categoryId:form.categoryId,status:props.id?form.status:undefined,skus:form.skus.map(s=>({id:props.id?s.id:undefined,specs:JSON.parse(s.specsText),priceCent:Math.round(Number(s.priceYuan)*100),stock:Number(s.stock),status:props.id?s.status:undefined}))}}
async function save(){if(!props.id&&!image.value)return ElMessage.warning('新增商品必须上传主图');saving.value=true;try{const data=payload();if(props.id)await merchantApi.updateProduct(props.id,data,image.value);else await merchantApi.createProduct(data,image.value);ElMessage.success('商品已保存');router.push('/products')}catch(e){ElMessage.error(e instanceof SyntaxError?'规格必须是合法 JSON':e.message)}finally{saving.value=false}}
onMounted(async()=>{try{categories.value=flatten(await merchantApi.categories());if(props.id){const p=await merchantApi.product(props.id);Object.assign(form,{title:p.title,description:p.description||'',categoryId:p.categoryId,status:p.status,skus:(p.skus||[]).map(s=>({id:s.id,specsText:s.specsJson,priceYuan:Number(s.priceCent)/100,stock:s.stock,status:s.status}))})}}catch(e){ElMessage.error(e.message)}})
</script>
<template><el-card><el-form label-width="100px"><el-form-item label="商品标题"><el-input v-model="form.title" maxlength="200"/></el-form-item><el-form-item label="店内分类"><el-select v-model="form.categoryId" style="width:280px"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="商品描述"><el-input v-model="form.description" type="textarea" :rows="5"/></el-form-item><el-form-item label="商品主图"><el-upload :auto-upload="false" :limit="1" :on-change="pick"><el-button>选择图片</el-button></el-upload></el-form-item><el-form-item v-if="id" label="上架状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0"/></el-form-item><el-divider>SKU 规格</el-divider><el-table :data="form.skus"><el-table-column label="规格 JSON"><template #default="s"><el-input v-model="s.row.specsText"/></template></el-table-column><el-table-column label="价格（元）"><template #default="s"><el-input-number v-model="s.row.priceYuan" :min="0.01" :precision="2"/></template></el-table-column><el-table-column label="库存"><template #default="s"><el-input-number v-model="s.row.stock" :min="0"/></template></el-table-column><el-table-column label="启用"><template #default="s"><el-switch v-model="s.row.status" :active-value="1" :inactive-value="0"/></template></el-table-column><el-table-column width="80"><template #default="s"><el-button link type="danger" :disabled="form.skus.length===1" @click="form.skus.splice(s.$index,1)">删除</el-button></template></el-table-column></el-table><el-button style="margin:14px 0" @click="addSku">添加 SKU</el-button><div><el-button @click="router.back()">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存商品</el-button></div></el-form></el-card></template>
